version: '3.8'

services:
  opensearch_adapter:
    build: .
    container_name: opensearch_adapter
    networks:
      - test_network
    restart: unless-stopped
    ports:
      - "8005:8000"  # Optional: expose health check endpoint

networks:
  test_network:
    external: true
